CarPurchase/CarPurchase/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', include('users.urls')),
    path('admin_login/', include('admins.urls')),



]

CarPurchase/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', include('users.urls')),
    path('admin_login/', include('admins.urls')),



]

CarPurchase/users/urls.py
from django.urls import path
from . import views

app_name = 'users_'

urlpatterns = [
    path('', views.user_login, name='user_login'),
    path('user_register_action/', views.user_register_action, name='user_register_action'),
    path('user_data_view/', views.user_data_view, name='user_data_view'),
    path('linear_regression/', views.linear_regression, name="linear_regression"),
    path('decision_tree/', views.decision_tree, name="decision_tree"),
    path('random_forest/', views.random_forest, name="random_forest"),
    path('support_vector_classifier/', views.support_vector_classifier, name="support_vector_classifier"),
    path('naive_bayes/', views.naive_bayes, name="naive_bayes"),
    path('k_nearest_neighbour/', views.k_nearest_neighbour, name="k_nearest_neighbour"),
    path('ann_results/', views.ann_results, name="ann_results"),
    path('user_prediction/', views.user_prediction, name="user_prediction"),


]

users/urls.py
from django.urls import path
from . import views

app_name = 'users_'

urlpatterns = [
    path('', views.user_login, name='user_login'),
    path('user_register_action/', views.user_register_action, name='user_register_action'),
    path('user_data_view/', views.user_data_view, name='user_data_view'),
    path('linear_regression/', views.linear_regression, name="linear_regression"),
    path('decision_tree/', views.decision_tree, name="decision_tree"),
    path('random_forest/', views.random_forest, name="random_forest"),
    path('support_vector_classifier/', views.support_vector_classifier, name="support_vector_classifier"),
    path('naive_bayes/', views.naive_bayes, name="naive_bayes"),
    path('k_nearest_neighbour/', views.k_nearest_neighbour, name="k_nearest_neighbour"),
    path('ann_results/', views.ann_results, name="ann_results"),
    path('user_prediction/', views.user_prediction, name="user_prediction"),


]

CarPurchase/users/models.py
from django.db import models


# Create your models here.
class UserRegistrationModel(models.Model):
    name = models.CharField(max_length=100)
    username = models.CharField(unique=True, max_length=100)
    password = models.CharField(max_length=100)
    email = models.CharField(unique=True, max_length=100)

    status = models.CharField(max_length=100, default="waiting")

    def __str__(self):
        return str(self.username)

    class Meta:
        db_table = 'UserRegistrations'

users/models.py
from django.db import models


# Create your models here.
class UserRegistrationModel(models.Model):
    name = models.CharField(max_length=100)
    username = models.CharField(unique=True, max_length=100)
    password = models.CharField(max_length=100)
    email = models.CharField(unique=True, max_length=100)

    status = models.CharField(max_length=100, default="waiting")

    def __str__(self):
        return str(self.username)

    class Meta:
        db_table = 'UserRegistrations'

CarPurchase/users/forms.py
from django import forms
from .models import UserRegistrationModel


class UserRegistrationForm(forms.ModelForm):
    name = forms.CharField(required=True,
                           max_length=100,
                           widget=forms.TextInput(
                               attrs={
                                   'class': 'form-control'
                               }
                           ))
    username = forms.CharField(required=True,
                               max_length=100,
                               widget=forms.TextInput(
                                   attrs={
                                       'class': 'form-control'
                                   }
                               ))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            'class': 'form-control'
        }
    ))
    status = forms.CharField(
        initial='waiting',
        widget=forms.HiddenInput(
            attrs={
                'class': 'form-control'
            }
        ))

    password = forms.CharField(required=True,
                               widget=forms.PasswordInput(
                                   attrs={
                                       'pattern': '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}',
                                       'title': 'Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters',
                                       'class': 'form-control',
                                   }
                               ))

    class Meta:
        model = UserRegistrationModel
        fields = '__all__'


class UserLoginForm(forms.Form):

    username = forms.CharField(required=True,
                               max_length=100,
                               widget=forms.TextInput(
                                   attrs={
                                       'class': 'form-control'
                                   }
                               ))


    password = forms.CharField(required=True,
                               widget=forms.PasswordInput(
                                   attrs={
                                       'pattern': '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}',
                                       'title': 'Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters',
                                       'class': 'form-control',
                                   }
                               ))

CarPurchase/users/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render
from .forms import (UserLoginForm, UserRegistrationForm)
from .models import UserRegistrationModel
import pandas as pd


# Create your views here.
def user_login(request):
    context = {'form': UserLoginForm()}
    if request.method == 'POST':
        print('=000=' * 40, request.POST)
        form = UserLoginForm(request.POST)
        print('VALID:', form.is_valid())
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            print('UserName:', username)
            print('Password:', password)
            try:
                user = UserRegistrationModel.objects.get(username=username, password=password)
                status = user.status
                if status == 'activated':
                    request.session['username'] = user.username
                    request.session['password'] = user.password
                    return render(request, 'users/user_home.html')
                else:
                    messages.success(request, 'Your A/C is not activated yet.')
                    return render(request, 'user_login.html', context)
            except Exception as e:
                pass
            messages.error(request, 'Invalid username or password.')
    context = {'form': UserLoginForm()}
    return render(request, 'user_login.html', context)


def user_register_action(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your request has been submitted, Admin will get back to you soon.')

    context = {
        'form': UserRegistrationForm()
    }
    return render(request, 'register.html', context)


def user_data_view(request):
    import pandas as pd
    from django.conf import settings
    import os
    path = os.path.join(settings.MEDIA_ROOT, 'cars.csv')
    df = pd.read_csv(path)
    df = df.to_html
    path = os.path.join(settings.MEDIA_ROOT, 'Automobile_data.csv')
    auto_df = pd.read_csv(path)
    auto_df = auto_df.to_html
    return render(request, 'users/data.html', {'data': df, "auto": auto_df})


def linear_regression(request):
    from .algorithms import AlgorithmUtility
    accuracy, precision, recall, f1score = AlgorithmUtility.calc_logistic_regression()
    return render(request, 'users/lg.html',
                  {'accuracy': accuracy, "precision": precision, "recall": recall, "f1score": f1score})


def decision_tree(request):
    from .algorithms import AlgorithmUtility
    accuracy, precision, recall, f1score = AlgorithmUtility.calc_decision_tree()
    return render(request, 'users/dt.html',
                  {'accuracy': accuracy, "precision": precision, "recall": recall, "f1score": f1score})


def random_forest(request):
    from .algorithms import AlgorithmUtility
    accuracy, precision, recall, f1score = AlgorithmUtility.calc_random_forest()
    return render(request, 'users/rf.html',
                  {'accuracy': accuracy, "precision": precision, "recall": recall, "f1score": f1score})


def support_vector_classifier(request):
    from .algorithms import AlgorithmUtility
    accuracy, precision, recall, f1score = AlgorithmUtility.calc_support_vector_classifier()
    return render(request, 'users/svm.html',
                  {'accuracy': accuracy, "precision": precision, "recall": recall, "f1score": f1score})


def naive_bayes(request):
    from .algorithms import AlgorithmUtility
    accuracy, precision, recall, f1score = AlgorithmUtility.calc_naive_bayes_classifier()
    return render(request, 'users/nv.html',
                  {'accuracy': accuracy, "precision": precision, "recall": recall, "f1score": f1score})


def k_nearest_neighbour(request):
    from .algorithms import AlgorithmUtility
    accuracy, precision, recall, f1score = AlgorithmUtility.calc_k_nearest_neighbour_classifier()
    return render(request, 'users/knn.html',
                  {'accuracy': accuracy, "precision": precision, "recall": recall, "f1score": f1score})


def ann_results(request):
    from .algorithms import AlgorithmUtility
    accuracy, precision, recall, f1score = AlgorithmUtility.calculate_ann_results()
    return render(request, 'users/ann.html',
                  {'accuracy': accuracy, "precision": precision, "recall": recall, "f1score": f1score})


def user_prediction(request):
    if request.method == "POST":
        price = int(request.POST.get("price"))
        SpareParts = int(request.POST.get("SpareParts"))
        CylinderVolume = int(request.POST.get("CylinderVolume"))
        ResalePrice = int(request.POST.get("ResalePrice"))
        CarssReview = int(request.POST.get("CarssReview"))
        test = [price, SpareParts, CylinderVolume, ResalePrice, CarssReview]
        from .algorithms import AlgorithmUtility
        rslt = AlgorithmUtility.test_user_date(test)
        if rslt[0] == 1:
            msg = "you Can Buy"
        else:
            msg = "Dont buy"
        return render(request, "users/Prediction_form.html", {"msg": msg, "features": test})
    else:
        return render(request, "users/Prediction_form.html", {})

users/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render
from .forms import (UserLoginForm, UserRegistrationForm)
from .models import UserRegistrationModel
import pandas as pd


# Create your views here.
def user_login(request):
    context = {'form': UserLoginForm()}
    if request.method == 'POST':
        print('=000=' * 40, request.POST)
        form = UserLoginForm(request.POST)
        print('VALID:', form.is_valid())
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            print('UserName:', username)
            print('Password:', password)
            try:
                user = UserRegistrationModel.objects.get(username=username, password=password)
                status = user.status
                if status == 'activated':
                    request.session['username'] = user.username
                    request.session['password'] = user.password
                    return render(request, 'users/user_home.html')
                else:
                    messages.success(request, 'Your A/C is not activated yet.')
                    return render(request, 'user_login.html', context)
            except Exception as e:
                pass
            messages.error(request, 'Invalid username or password.')
    context = {'form': UserLoginForm()}
    return render(request, 'user_login.html', context)


def user_register_action(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your request has been submitted, Admin will get back to you soon.')

    context = {
        'form': UserRegistrationForm()
    }
    return render(request, 'register.html', context)


def user_data_view(request):
    import pandas as pd
    from django.conf import settings
    import os
    path = os.path.join(settings.MEDIA_ROOT, 'cars.csv')
    df = pd.read_csv(path)
    df = df.to_html
    path = os.path.join(settings.MEDIA_ROOT, 'Automobile_data.csv')
    auto_df = pd.read_csv(path)
    auto_df = auto_df.to_html
    return render(request, 'users/data.html', {'data': df, "auto": auto_df})


def linear_regression(request):
    from .algorithms import AlgorithmUtility
    accuracy, precision, recall, f1score = AlgorithmUtility.calc_logistic_regression()
    return render(request, 'users/lg.html',
                  {'accuracy': accuracy, "precision": precision, "recall": recall, "f1score": f1score})


def decision_tree(request):
    from .algorithms import AlgorithmUtility
    accuracy, precision, recall, f1score = AlgorithmUtility.calc_decision_tree()
    return render(request, 'users/dt.html',
                  {'accuracy': accuracy, "precision": precision, "recall": recall, "f1score": f1score})


def random_forest(request):
    from .algorithms import AlgorithmUtility
    accuracy, precision, recall, f1score = AlgorithmUtility.calc_random_forest()
    return render(request, 'users/rf.html',
                  {'accuracy': accuracy, "precision": precision, "recall": recall, "f1score": f1score})


def support_vector_classifier(request):
    from .algorithms import AlgorithmUtility
    accuracy, precision, recall, f1score = AlgorithmUtility.calc_support_vector_classifier()
    return render(request, 'users/svm.html',
                  {'accuracy': accuracy, "precision": precision, "recall": recall, "f1score": f1score})


def naive_bayes(request):
    from .algorithms import AlgorithmUtility
    accuracy, precision, recall, f1score = AlgorithmUtility.calc_naive_bayes_classifier()
    return render(request, 'users/nv.html',
                  {'accuracy': accuracy, "precision": precision, "recall": recall, "f1score": f1score})


def k_nearest_neighbour(request):
    from .algorithms import AlgorithmUtility
    accuracy, precision, recall, f1score = AlgorithmUtility.calc_k_nearest_neighbour_classifier()
    return render(request, 'users/knn.html',
                  {'accuracy': accuracy, "precision": precision, "recall": recall, "f1score": f1score})


def ann_results(request):
    from .algorithms import AlgorithmUtility
    accuracy, precision, recall, f1score = AlgorithmUtility.calculate_ann_results()
    return render(request, 'users/ann.html',
                  {'accuracy': accuracy, "precision": precision, "recall": recall, "f1score": f1score})


def user_prediction(request):
    if request.method == "POST":
        price = int(request.POST.get("price"))
        SpareParts = int(request.POST.get("SpareParts"))
        CylinderVolume = int(request.POST.get("CylinderVolume"))
        ResalePrice = int(request.POST.get("ResalePrice"))
        CarssReview = int(request.POST.get("CarssReview"))
        test = [price, SpareParts, CylinderVolume, ResalePrice, CarssReview]
        from .algorithms import AlgorithmUtility
        rslt = AlgorithmUtility.test_user_date(test)
        if rslt[0] == 1:
            msg = "you Can Buy"
        else:
            msg = "Dont buy"
        return render(request, "users/Prediction_form.html", {"msg": msg, "features": test})
    else:
        return render(request, "users/Prediction_form.html", {})

users/templates/users/Prediction_form.html
{% extends 'users/user_base.html' %}
{% block content %}

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
#


 <section id="intro">

    <div class="intro-text">
<!--        <div class="container" style="margin-top:-200px;">-->

      <p><h3 align="center" style="color:green;font-weight:bold;">Classification Results</h3></p>
      <!--<a href="#about" class="btn-get-started scrollto">Get Started</a>-->
        <center>
            <h3>Prediction Form</h3>
            <span>
                <h3>The Feature {{features}} <font style="color:RED">{{msg}}</font></h3>
            </span>
        <form action="{% url 'users_:user_prediction'%}" method="post">
            {%csrf_token%}
            <table>
                <tr>
                    <td>Price</td><td><input type="number" max="3"  min="1"  title="must contain 1 to 3 only" name="price" required/></td><td>Price range 1 to 3</td>
                </tr>
                 <tr>
                    <td>Spare Parts</td><td><input type="number" max="3"  min="1"  title="must contain 1 to 3 only" name="SpareParts" required></td><td>Spare Parts 1 to 3</td>
                </tr>
                <tr>
                    <td>Cylinder Volume</td><td><input type="number" max="3"  min="1"  title="must contain 1 to 3 only" name="CylinderVolume" required></td><td>Cylinder Volume 1 to 3</td>
                </tr>
                <tr>
                    <td>Resale Price</td><td><input type="number"max="3"  min="1"  title="must contain 1 to 3 only" name="ResalePrice" required></td><td>Resale Price 1 to 3</td>
                </tr>

                <tr>
                    <td>Cars Review</td><td><input type="number" max="1"  min="0"  title="must contain 0 to 1 only" name="CarssReview" required></td><td>Cars's Review 0 to 1</td>
                </tr>

                <tr>
                    <td></td><td><input type="submit" name="submit" value="Submit"></td>
                </tr>


            </table>
        </form>
        </center>
    </div>
  </section>




{% endblock %}

users/templates/users/ann.html
{% extends 'users/user_base.html' %}
{% block content %}

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
#


 <section id="intro">

    <div class="intro-text">
<!--        <div class="container" style="margin-top:-200px;">-->

      <p><h3 align="center" style="color:green;font-weight:bold;">Classification Results</h3></p>
      <!--<a href="#about" class="btn-get-started scrollto">Get Started</a>-->
        <center>
            <h3>Artificial Neural Network Result</h3>
        <table>
            <tr><td>Accuracy</td><td>{{accuracy}}</td> </tr>
            <tr><td>Precision</td><td>{{precision}}</td> </tr>
            <tr><td>Recall</td><td>{{recall}}</td> </tr>
            <tr><td>F1_Score</td><td>{{f1score}}</td> </tr>

        </table>
        </center>
    </div>
  </section>




{% endblock %}

users/templates/users/data.html
{% extends 'users/user_base.html' %}
{% block content %}

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
#


 <section id="intro">

    <div class="intro-text">
<!--        <div class="container" style="margin-top:-200px;">-->

      <p><h3 align="center" style="color:green;font-weight:bold;">View Data</h3></p>
      <!--<a href="#about" class="btn-get-started scrollto">Get Started</a>-->
        <ol>
                <li>1 Means  Low or Normal</li>
                <li>2 Means  Medium or Affordable</li>
                <li>3 Means  High or Expensive</li>
            </ol>
        <span>In Review 1 Means Positive, 0 Means Negative</span>
        <span>In Buy 1 Means Buy, 0 Means Not Buy</span>
        <center>
<h2>Pre Processed Data</h2>
        {{data|safe}}

            <h3>Dateset</h3>
            {{auto|safe}}
            </center>
    </div>
  </section>




{% endblock %}

users/templates/users/dt.html
{% extends 'users/user_base.html' %}
{% block content %}

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
#


 <section id="intro">

    <div class="intro-text">
<!--        <div class="container" style="margin-top:-200px;">-->

      <p><h3 align="center" style="color:green;font-weight:bold;">Classification Results</h3></p>
      <!--<a href="#about" class="btn-get-started scrollto">Get Started</a>-->
        <center>
            <h3>Decision Tree Results</h3>
        <table>
            <tr><td>Accuracy</td><td>{{accuracy}}</td> </tr>
            <tr><td>Precision</td><td>{{precision}}</td> </tr>
            <tr><td>Recall</td><td>{{recall}}</td> </tr>
            <tr><td>F1_Score</td><td>{{f1score}}</td> </tr>

        </table>
        </center>
    </div>
  </section>




{% endblock %}

users/templates/users/knn.html
{% extends 'users/user_base.html' %}
{% block content %}

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
#


 <section id="intro">

    <div class="intro-text">
<!--        <div class="container" style="margin-top:-200px;">-->

      <p><h3 align="center" style="color:green;font-weight:bold;">Classification Results</h3></p>
      <!--<a href="#about" class="btn-get-started scrollto">Get Started</a>-->
        <center>
            <h3>K-nearest_Neighbour</h3>
        <table>
            <tr><td>Accuracy</td><td>{{accuracy}}</td> </tr>
            <tr><td>Precision</td><td>{{precision}}</td> </tr>
            <tr><td>Recall</td><td>{{recall}}</td> </tr>
            <tr><td>F1_Score</td><td>{{f1score}}</td> </tr>

        </table>
        </center>
    </div>
  </section>




{% endblock %}

users/templates/users/lg.html
{% extends 'users/user_base.html' %}
{% block content %}

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
#


 <section id="intro">

    <div class="intro-text">
<!--        <div class="container" style="margin-top:-200px;">-->

      <p><h3 align="center" style="color:green;font-weight:bold;">Classification Results</h3></p>
      <!--<a href="#about" class="btn-get-started scrollto">Get Started</a>-->
        <center>
            <h3>Logistic Regression Results</h3>
        <table>
            <tr><td>Accuracy</td><td>{{accuracy}}</td> </tr>
            <tr><td>Precision</td><td>{{precision}}</td> </tr>
            <tr><td>Recall</td><td>{{recall}}</td> </tr>
            <tr><td>F1_Score</td><td>{{f1score}}</td> </tr>

        </table>
        </center>
    </div>
  </section>




{% endblock %}

users/templates/users/nv.html
{% extends 'users/user_base.html' %}
{% block content %}

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
#


 <section id="intro">

    <div class="intro-text">
<!--        <div class="container" style="margin-top:-200px;">-->

      <p><h3 align="center" style="color:green;font-weight:bold;">Classification Results</h3></p>
      <!--<a href="#about" class="btn-get-started scrollto">Get Started</a>-->
        <center>
            <h3>Naive Bayes</h3>
        <table>
            <tr><td>Accuracy</td><td>{{accuracy}}</td> </tr>
            <tr><td>Precision</td><td>{{precision}}</td> </tr>
            <tr><td>Recall</td><td>{{recall}}</td> </tr>
            <tr><td>F1_Score</td><td>{{f1score}}</td> </tr>

        </table>
        </center>
    </div>
  </section>




{% endblock %}

users/templates/users/user_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>
        {% block title %}
        {% endblock %}
    </title>

    <meta content="" name="description">

    <meta content="" name="keywords">

    <!-- Favicons -->
{#    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">#}
    <link href="{% static 'assets/img/logo.png' %}" rel="icon">

    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">


</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="header fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

        <a href="#" class="logo d-flex align-items-center">
            <img src="{% static 'assets/img/logo.png' %}" alt="">
            <span>CarPurchase</span>
        </a>

        <nav id="navbar" class="navbar">

            {#        url preparation#}


            <ul>
                <li>
                    <a class="nav-link scrollto active" href="#">Home</a>
                </li>
                <li>
                    <a class="nav-link {% if request.path == user_data_view %} active {% endif %}"
                       href="{% url 'users_:user_data_view' %}">View Data</a>
                </li>
                <li><a class="nav-link scrollto" href="{%url 'users_:linear_regression'%}">LR </a></li>
                <li><a class="nav-link scrollto" href="{%url 'users_:decision_tree'%}">D Tree </a></li>
                <li><a class="nav-link scrollto" href="{%url 'users_:random_forest'%}">RF</a></li>
                <li><a class="nav-link scrollto" href="{%url 'users_:support_vector_classifier'%}">SVM</a></li>
                <li><a class="nav-link scrollto" href="{%url 'users_:naive_bayes'%}">NB</a></li>
                <li><a class="nav-link scrollto" href="{%url 'users_:k_nearest_neighbour'%}">KNN</a></li>
                <li><a class="nav-link scrollto" href="{%url 'users_:ann_results'%}">ANN</a></li>
                <li><a class="nav-link scrollto" href="{%url 'users_:user_prediction'%}">Prediction</a></li>
                <li><a class="getstarted scrollto" href="{% url 'index' %}">Logout</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

    </div>
</header><!-- End Header -->

<!-- Body Section -->
{% block content %}

{% endblock %}



<!-- ======= Footer ======= -->
<footer id="footer" class="footer fixed-bottom">


    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span>CarPurchase</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            Designed by <a href="https://www.datapointinfo.com/">Datapoint</a>
        </div>
    </div>
</footer><!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
<script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
<script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/purecounter/purecounter.js' %}"></script>
<script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>