CarPurchase/CarPurchase/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', include('users.urls')),
    path('admin_login/', include('admins.urls')),



]

CarPurchase/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', include('users.urls')),
    path('admin_login/', include('admins.urls')),



]

admins/urls.py
from django.urls import path
from . import views

app_name = 'admins_'

urlpatterns = [

    path('admin_login/', views.admin_login, name='admin_login'),
    path('admin_home/', views.admin_home, name='admin_home'),
    path('users_list/', views.users_list, name='users_list'),
    path('activate_user/<str:id>', views.activate_user, name='activate_user'),
    path('admin_results/', views.admin_results, name='admin_results'),

]

users/urls.py
from django.urls import path
from . import views

app_name = 'users_'

urlpatterns = [
    path('', views.user_login, name='user_login'),
    path('user_register_action/', views.user_register_action, name='user_register_action'),
    path('user_data_view/', views.user_data_view, name='user_data_view'),
    path('linear_regression/', views.linear_regression, name="linear_regression"),
    path('decision_tree/', views.decision_tree, name="decision_tree"),
    path('random_forest/', views.random_forest, name="random_forest"),
    path('support_vector_classifier/', views.support_vector_classifier, name="support_vector_classifier"),
    path('naive_bayes/', views.naive_bayes, name="naive_bayes"),
    path('k_nearest_neighbour/', views.k_nearest_neighbour, name="k_nearest_neighbour"),
    path('ann_results/', views.ann_results, name="ann_results"),
    path('user_prediction/', views.user_prediction, name="user_prediction"),


]

templates/admin_login.html
{% extends 'base.html' %}
{% block title %}
    Admin Login
{% endblock %}

{% block content %}
    <style>
        .error {
            list-style: none;
            color: red;
        }
    </style>
    {% load static %}
    <section id="hero" class="hero d-flex align-items-center">

        <div class="container">
            <div class="row offset-md-3 col-md-10 ">
                <div class="col-lg-6 d-flex flex-column justify-content-center">

                    <div data-aos="fade-up" data-aos-delay="600">
                        <div class="text-center text-lg-start">

                            <form action="{% url 'admins_:admin_login' %}" method="POST" class="form-group"
                                  style="background-color:#ced4da; padding: 30px;margin-top: 5rem; border-radius: 2%">
                                <legend align="center">
                                    <img src="{% static 'assets/img/admin.png' %}" alt="User" width="15%">
                                    <br>
                                    Admin
                                </legend>
                                {% csrf_token %}
                                {{ form.as_p }}

                                <p align="center">
                                    <input type="submit" value="Sign in" class="btn btn-primary btn-lg px-lg-5">
                                    &nbsp;
                                    <input type="reset" value="Reset" class="btn btn-outline-danger btn-lg">
                                </p>


                                <!-- Messages -->
                                {% if messages %}
                                    <ul class="messages">
                                        {% for message in messages %}
                                            <li{% if message.tags %}
                                                class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </form>

                        </div>
                    </div>
                </div>

            </div>
        </div>

    </section><!-- End Hero -->


{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>
        {% block title %}
        {% endblock %}
    </title>

    <meta content="" name="description">

    <meta content="" name="keywords">

    <!-- Favicons -->
{#    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">#}
    <link href="{% static 'assets/img/logo.png' %}" rel="icon">

    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">


</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="header fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

        <a href="/" class="logo d-flex align-items-center">
            <img src="{% static 'assets/img/logo.png' %}" alt="">
            <span>CarPurchase</span>
        </a>

        <nav id="navbar" class="navbar">

            {#        url preparation#}
            {% url 'index' as index %}
            {% url 'users_:user_login' as user_login %}
            {% url 'admins_:admin_login' as  admin_login %}

            <ul>
                <li>
                    <a class="nav-link scrollto {% if request.path == index %} active {% endif %}" href="/">Home</a>
                </li>
                <li>
                    <a class="nav-link {% if request.path == user_login %} active {% endif %}"
                       href="{% url 'users_:user_login' %}">Users</a>
                </li>
                <li>
                    <a class="nav-link scrollto {% if request.path == admin_login %}active {% endif %}"
                       href="{% url 'admins_:admin_login' %}">Admin</a>
                </li>

                <li><a class="getstarted scrollto" href="{% url 'register' %}">Register</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

    </div>
</header><!-- End Header -->

<!-- Body Section -->
{% block content %}

{% endblock %}



<!-- ======= Footer ======= -->
<footer id="footer" class="footer">


    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span>CarPurchase</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            Designed by <a href="https://www.datapointinfo.com/">Datapoint</a>
        </div>
    </div>
</footer><!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
<script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
<script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/purecounter/purecounter.js' %}"></script>
<script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/contacts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">

        <div class="container" data-aos="fade-up">

            <header class="section-header">
                <h2>Contact</h2>
                <p>Contact Us</p>
            </header>

            <div class="row gy-4">

                <div class="col-lg-6">

                    <div class="row gy-4">
                        <div class="col-md-6">
                            <div class="info-box">
                                <i class="bi bi-geo-alt"></i>
                                <h3>Address</h3>
                                <p>A108 Adam Street,<br>New York, NY 535022</p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="info-box">
                                <i class="bi bi-telephone"></i>
                                <h3>Call Us</h3>
                                <p>+1 5589 55488 55<br>+1 6678 254445 41</p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="info-box">
                                <i class="bi bi-envelope"></i>
                                <h3>Email Us</h3>
                                <p>info@example.com<br>contact@example.com</p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="info-box">
                                <i class="bi bi-clock"></i>
                                <h3>Open Hours</h3>
                                <p>Monday - Friday<br>9:00AM - 05:00PM</p>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="col-lg-6">
                    <form action="forms/contact.php" method="post" class="php-email-form">
                        <div class="row gy-4">

                            <div class="col-md-6">
                                <input type="text" name="name" class="form-control" placeholder="Your Name" required>
                            </div>

                            <div class="col-md-6 ">
                                <input type="email" class="form-control" name="email" placeholder="Your Email" required>
                            </div>

                            <div class="col-md-12">
                                <input type="text" class="form-control" name="subject" placeholder="Subject" required>
                            </div>

                            <div class="col-md-12">
                                <textarea class="form-control" name="message" rows="6" placeholder="Message"
                                          required></textarea>
                            </div>

                            <div class="col-md-12 text-center">
                                <div class="loading">Loading</div>
                                <div class="error-message"></div>
                                <div class="sent-message">Your message has been sent. Thank you!</div>

                                <button type="submit">Send Message</button>
                            </div>

                        </div>
                    </form>

                </div>

            </div>

        </div>

    </section><!-- End Contact Section -->


</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}
    Car Purchase
{% endblock %}
{% block content %}
    {% load static %}
    <!-- ======= Hero Section ======= -->
    <section id="hero" class="hero d-flex align-items-center">

        <div class="container">
            <div class="row">
                <div class="col-lg-6 d-flex flex-column justify-content-center">
                    <h1 data-aos="fade-up"> Predicting Car Purchase Based on Customers Demands</h1>
                    <h2 data-aos="fade-up" data-aos-delay="400">We are team of talented designers making websites with
                        Bootstrap</h2>
                    <div data-aos="fade-up" data-aos-delay="600">
                        <div class="text-center text-lg-start">
                            <a href="#about"
                               class="btn-get-started scrollto d-inline-flex align-items-center justify-content-center align-self-center">
                                <span>Get Started</span>
                                <i class="bi bi-arrow-right"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 hero-img" data-aos="zoom-out" data-aos-delay="200">
                    <img src="{% static 'assets/img/car.png' %}" class="img-fluid" alt="">
                </div>
            </div>
        </div>

    </section><!-- End Hero -->

    <main id="main">
        <!-- ======= About Section ======= -->
        <section id="about" class="about">

            <div class="container" data-aos="fade-up">
                <div class="row gx-lg-0">

                    <div class="col-lg-6 d-flex flex-column justify-content-center" data-aos="fade-up"
                         data-aos-delay="200">
                        <div class="content">
                            <h3>
                                Abstract

                            </h3>
                            <h2>
                                The automobile industry is one of the prominent
                                industries for the national economy.

                            </h2>
                            <p style="text-align: justify">
                                Day by day car is getting
                                popular for the private transport system. The customer needs
                                review when he wants to buy the right vehicle, especially the car.
                                Because it is a very costly vehicle. There are many conditions and
                                factors ...
                            </p>
                            <div class="text-center text-lg-start">
                                <a href="#faq"
                                   class="btn-read-more d-inline-flex align-items-center justify-content-center align-self-center">
                                    <span>Read More</span>
                                    <i class="bi bi-arrow-right"></i>
                                </a>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6 d-flex align-items-center" data-aos="zoom-out" data-aos-delay="200">
                        {#                                    <img src="{% static 'assets/img/about.jpg' %}" class="img-fluid" alt="">#}
                        <img src="{% static 'assets/cars/car2.png' %}" class="img-fluid" alt="">

                    </div>

                </div>
            </div>

        </section><!-- End About Section -->


        <!-- ======= F.A.Q Section ======= -->
        <section id="faq" class="faq">

            <div class="container" data-aos="fade-up">

                <header class="section-header">
                    <h2>Information </h2>
                    <p>Information About This Application</p>
                </header>

                <div class="row">
                    <div class="col-lg-12">
                        <!-- F.A.Q List 1-->
                        <div class="accordion accordion-flush" id="faqlist1">
                            <div class="accordion-item">
                                <h2 class="accordion-header">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                            data-bs-target="#faq-content-1">
                                        Abstration About This Project
                                    </button>
                                </h2>
                                <div id="faq-content-1" class="accordion-collapse collapse" data-bs-parent="#faqlist1">
                                    <div class="accordion-body" style="text-align: justify">
                                        The automobile industry is one of the prominent
                                        industries for the national economy. Day by day car is getting
                                        popular for the private transport system. The customer needs
                                        review when he wants to buy the right vehicle, especially the car.
                                        Because it is a very costly vehicle. There are many conditions and
                                        factors matter before buying a new car like spare parts, cylinder
                                        volume, headlight and especially price. So deciding everything,
                                        it is important for the customer to make the right choice of
                                        purchase which can satisfy all the criteria. Our goal is to help
                                        the customer to make the right decision whether he will buy a car
                                        or not. Therefore we wanted to build a technique for decision
                                        making in-car buy system. That’s why we propose some wellknown algorithms to get
                                        better
                                        accuracy for a car purchase in our
                                        paper. We applied those algorithms in our dataset which contains
                                        50 data. Among them, Support Vector Machine(SVM) gives the
                                        best result with 86.7% accuracy of prediction. In this paper,
                                        we have also revealed the comparative results using different
                                        algorithms precision, recall and F1 score for all data samples.
                                        Index Terms—Supervised Machine Learning, Naive Bayes,
                                        Random Forest tree, Support Vector Machine, KNN, Accuracy,
                                        Cosine Similarity
                                    </div>
                                </div>
                            </div>

                            <div class="accordion-item">
                                <h2 class="accordion-header">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                            data-bs-target="#faq-content-2">
                                        Limitations And Future Work
                                    </button>
                                </h2>
                                <div id="faq-content-2" class="accordion-collapse collapse" data-bs-parent="#faqlist1">
                                    <div class="accordion-body" style="text-align: justify">
                                        We have used 5 features for predicting the final output. in
                                        future we will collect more features for prediction and increase
                                        our dataset. We will use a more efficient technique to get
                                        better accuracy. We will intend to apply some more advanced
                                        machine learning techniques like Fuzzy logic, Decision Tree,
                                        Artificial Neural Network, Ordinary Least Squares Regression
                                        (OLSR), Fuzzy logic etc as our future work. This work can
                                        be enlarged by choosing more features for classification also.
                                    </div>
                                </div>
                            </div>

                            <div class="accordion-item">
                                <h2 class="accordion-header">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                            data-bs-target="#faq-content-3">
                                        Conclusion
                                    </button>
                                </h2>
                                <div id="faq-content-3" class="accordion-collapse collapse" data-bs-parent="#faqlist1">
                                    <div class="accordion-body">
                                        In our study, we mainly focused on Customer’s review
                                        and we have used Cosine Similarity to analyze customer’s
                                        review. Then we applied several algorithms on our dataset. We
                                        have compared those algorithms according to their accuracy.
                                        Support Vector Machine has given the highest accuracy among
                                        all the algorithms.
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

            </div>

        </section><!-- End F.A.Q Section -->


    </main><!-- End #main -->

{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block title %}User Registration {% endblock %}

{% block content %}
    <style>
        .success {
            list-style: none;
            color: blue;
        }
    </style>
    {% load static %}
    <section id="hero" class="hero d-flex align-items-center" style="margin-top: 100px;">

        <div class="container">
            <div class="row offset-md-3 col-md-10 ">
                <div class="col-lg-6 d-flex flex-column justify-content-center">

                    <div data-aos="fade-up" data-aos-delay="600">
                        <div class="text-center text-lg-start">

                            <form action="{% url 'users_:user_register_action' %}" method="POST" class="form-group"
                                  style="background-color:#ced4da; padding: 30px;
                                   border-radius: 2%">
                                <legend align="center">
                                    <img src="{% static 'assets/img/user.png' %}" alt="User" width="15%">
                                    <br>
                                    SignUp
                                </legend>
                                {% csrf_token %}
                                {{ form.as_p }}

                                <p align="center">
                                    <input type="submit" value="Save" class="btn btn-primary btn-lg px-lg-5">
                                    &nbsp;
                                    <input type="reset" value="Reset" class="btn btn-outline-danger btn-lg">
                                </p>

                                <!-- Messages -->

                                    {% if messages %}
                                        <ul class="messages">
                                            {% for message in messages %}
                                                <li{% if message.tags %}
                                                    class="{{ message.tags }}"{% endif %}>
                                                    {{ message }}
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}

                            </form>
                        </div>
                    </div>
                </div>

            </div>

        </div>


    </section><!-- End Hero -->

{% endblock %}

templates/user_login.html
{% extends 'base.html' %}
{% block title %}User Sign in {% endblock %}

{% block content %}
    <style>

        .error, .success, .info {
            list-style: none;
        }

        .success {
            list-style: none;
            color: blue;
        }

        .error, .info {
            list-style: none;
            color: red;
        }
    </style>
    {% load static %}
    <section id="hero" class="hero d-flex align-items-center">

        <div class="container">
            <div class="row offset-md-3 col-md-10 ">
                <div class="col-lg-6 d-flex flex-column justify-content-center">

                    <div data-aos="fade-up" data-aos-delay="600">
                        <div class="text-center text-lg-start">

                            <form action="{% url 'users_:user_login' %}" method="POST" class="form-group"
                                  style="background-color:#ced4da; padding: 30px;margin-top: 5rem; border-radius:2%">
                                <legend align="center">
                                    <img src="{% static 'assets/img/user.png' %}" alt="User" width="15%">
                                    <br>
                                    User
                                </legend>
                                {% csrf_token %}
                                {{ form.as_p }}

                                <p align="center">
                                    <input type="submit" value="Sign in" class="btn btn-primary btn-lg px-lg-5">
                                    &nbsp;
                                    <input type="reset" value="Reset" class="btn btn-outline-danger btn-lg">
                                </p>


                                <!-- Messages -->
                                {% if messages %}
                                    <ul class="messages">
                                        {% for message in messages %}
                                            <li{% if message.tags %}
                                                class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}

                            </form>

                        </div>
                    </div>
                </div>

            </div>
        </div>

    </section><!-- End Hero -->


{% endblock %}