CarPurchase/CarPurchase/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', include('users.urls')),
    path('admin_login/', include('admins.urls')),



]

CarPurchase/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', include('users.urls')),
    path('admin_login/', include('admins.urls')),



]

admins/urls.py
from django.urls import path
from . import views

app_name = 'admins_'

urlpatterns = [

    path('admin_login/', views.admin_login, name='admin_login'),
    path('admin_home/', views.admin_home, name='admin_home'),
    path('users_list/', views.users_list, name='users_list'),
    path('activate_user/<str:id>', views.activate_user, name='activate_user'),
    path('admin_results/', views.admin_results, name='admin_results'),

]

users/urls.py
from django.urls import path
from . import views

app_name = 'users_'

urlpatterns = [
    path('', views.user_login, name='user_login'),
    path('user_register_action/', views.user_register_action, name='user_register_action'),
    path('user_data_view/', views.user_data_view, name='user_data_view'),
    path('linear_regression/', views.linear_regression, name="linear_regression"),
    path('decision_tree/', views.decision_tree, name="decision_tree"),
    path('random_forest/', views.random_forest, name="random_forest"),
    path('support_vector_classifier/', views.support_vector_classifier, name="support_vector_classifier"),
    path('naive_bayes/', views.naive_bayes, name="naive_bayes"),
    path('k_nearest_neighbour/', views.k_nearest_neighbour, name="k_nearest_neighbour"),
    path('ann_results/', views.ann_results, name="ann_results"),
    path('user_prediction/', views.user_prediction, name="user_prediction"),


]

admins/templates/admins/admin_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>
        {% block title %}
        {% endblock %}
    </title>

    <meta content="" name="description">

    <meta content="" name="keywords">

    <!-- Favicons -->
{#    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">#}
    <link href="{% static 'assets/img/logo.png' %}" rel="icon">

    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">


</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="header fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

        <a href="{% url 'admins_:admin_home' %}" class="logo d-flex align-items-center">
            <img src="{% static 'assets/img/logo.png' %}" alt="">
            <span>CarPurchase</span>
        </a>

        <nav id="navbar" class="navbar">

            {#        url preparation#}
            {% url 'admins_:admin_home' as admin_home %}
            {% url 'users_:user_login' as user_login %}
            {% url 'admins_:admin_login' as  admin_login %}


            <ul>
                <li>
                    <a class="nav-link scrollto {% if request.path == admin_home %} active {% endif %}"
                       href="{% url 'admins_:admin_home' %}">Home</a>
                </li>
                <li>
                    <a class="nav-link {% if request.path == user_login %} active {% endif %}"
                       href="{% url 'admins_:users_list' %}">Users</a>
                </li>
                <li>
                    <a class="nav-link scrollto {% if request.path == admin_login %}active {% endif %}"
                       href="{%url 'admins_:admin_results'%}">ML Results</a>
                </li>

                <li><a class="getstarted scrollto" href="{% url 'admins_:admin_login' %}">Logout</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

    </div>
</header><!-- End Header -->

<!-- Body Section -->
{% block content %}

{% endblock %}



<!-- ======= Footer ======= -->
{#<footer id="footer" class="footer fixed-bottom">#}
<footer id="footer" class="footer">


    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span>CarPurchase</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            Designed by <a href="https://www.datapointinfo.com/">Datapoint</a>
        </div>
    </div>
</footer><!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
<script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
<script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/purecounter/purecounter.js' %}"></script>
<script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

admins/templates/admins/admin_home.html
{% extends 'admins/admin_base.html' %}

{% block title %}
    Admin Home
{% endblock %}


{% block content %}

    {% load static %}
    <section id="hero" class="hero d-flex align-items-center">

        <div class="container">
            <div class="row offset-md-3 col-md-10 ">
                <div class="col-lg-6 d-flex flex-column justify-content-center">

                    <div data-aos="fade-up" data-aos-delay="600">
                        <div class="text-center text-lg-start">

                            <h1>Admin Here</h1>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </section><!-- End Hero -->


{% endblock %}

admins/templates/admins/admin_results.html
{% extends 'admins/admin_base.html' %}

{% block title %}
Admin Home
{% endblock %}


{% block content %}

{% load static %}
<section id="hero" class="hero d-flex align-items-center">

    <div class="container">
        <div class="row offset-md-3 col-md-10 ">
            <div class="col-lg-6 d-flex flex-column justify-content-center">

                <div data-aos="fade-up" data-aos-delay="600">
                    <div class="text-center text-lg-start">

                        <h3>Admin View Results</h3>
                        <table class ="center"></table>
                        <table class="table" border="2" >
                            <tr>
                                <th>S.NO</th>
                                <th>Algorithm</th>
                                <th>Accuracy</th>
                                <th>Precession</th>
                                <th>Recall</th>
                                <th>F1-Score</th>
                            </tr>
                            <tr>
                                <td>1</td>
                                <td>Logistic Regression</td>
                                <td>{{lg.lg_accuracy}}</td>
                                <td>{{lg.lg_precision}}</td>
                                <td>{{lg.lg_recall}}</td>
                                <td>{{lg.lg_f1score}}</td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td>Decision Tree</td>
                                <td>{{dt.dt_accuracy}}</td>
                                <td>{{dt.dt_precision}}</td>
                                <td>{{dt.dt_recall}}</td>
                                <td>{{dt.dt_f1score}}</td>
                            </tr>
                            <tr>
                                <td>3</td>
                                <td>Random Forest</td>
                                <td>{{rf.rf_accuracy}}</td>
                                <td>{{rf.rf_precision}}</td>
                                <td>{{rf.rf_recall}}</td>
                                <td>{{rf.rf_f1score}}</td>
                            </tr>
                            <tr>
                                <td>4</td>
                                <td>Support Vector Machine</td>
                                <td>{{svm.svm_accuracy}}</td>
                                <td>{{svm.svm_precision}}</td>
                                <td>{{svm.svm_recall}}</td>
                                <td>{{svm.svm_f1score}}</td>
                            </tr>

                            <tr>
                                <td>5</td>
                                <td>Naive bayes</td>
                                <td>{{nb.nb_accuracy}}</td>
                                <td>{{nb.nb_precision}}</td>
                                <td>{{nb.nb_recall}}</td>
                                <td>{{nb.nb_f1score}}</td>
                            </tr>
                            <tr>
                                <td>6</td>
                                <td>K-Nearest Neighbour</td>
                                <td>{{knn.knn_accuracy}}</td>
                                <td>{{knn.knn_precision}}</td>
                                <td>{{knn.knn_recall}}</td>
                                <td>{{knn.knn_f1score}}</td>
                            </tr>
                            <tr>
                                <td>7</td>
                                <td>Artificail Neural Network</td>
                                <td>{{ann.ann_accuracy}}</td>
                                <td>{{ann.ann_precision}}</td>
                                <td>{{ann.ann_recall}}</td>
                                <td>{{ann.ann_f1score}}</td>
                            </tr>

                        </table>

                    </div>
                </div>
            </div>

        </div>
    </div>

</section><!-- End Hero -->


{% endblock %}

admins/templates/admins/users_list.html
{% extends 'admins/admin_base.html' %}

{% block title %}
    User's List
{% endblock %}


{% block content %}
    <style>
        .container {
            font-family: "Book Antiqua";

        }
    </style>

    {% load static %}
    <div class="container">
        <div class="row">
            <div class="col">
                <table class="table table-striped table-hover" style="margin-top: 10rem;">
                    <caption align="top" style="text-align: center;font-size: 2rem;">User List</caption>
                    <thead class="">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Username</th>
                        <th scope="col">Email</th>
                        <th scope="col">Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users_list %}
                        <tr>
                            <th scope="row">{{ forloop.counter0|add:users_list.start_index }}</th>
                            <td>{{ user.name }}</td>
                            <td>{{ user.username }}</td>
                            <td>{{ user.email }}</td>
                            <td>
                                <a href="{% url 'admins_:activate_user' user.id %}" class=" btn btn-link">
                                    {{ user.status }}
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <!-- Pagination-->
                <div class="container p-4">
                    <div class="pagination justify-content-center">
                    <span class="step-links">
                        {% if users_list.has_previous %}
                            <a href="?page=1">&laquo; first </a>
                            <a href="?page={{ users_list.previous_page_number }}"> previous &nbsp;</a>
                        {% endif %}
                    </span>
                        <span class="current">
                        Page{{ users_list.number }}  of  {{ users_list.paginator.num_pages }}
                            &nbsp;
                    </span>

                        {% if users_list.has_next %}
                            <a href="?page={{ users_list.next_page_number }}"> next &nbsp; </a>
                            <a href="?page={{ users_list.paginator.num_pages }}"> last &raquo;</a>
                        {% endif %}
                    </div>
                </div>
                <!-- end of Pagination -->

            </div>

        </div>
    </div>





{% endblock %}